# Generated by Django 4.2.5 on 2023-09-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPFEtrade', '0002_remove_market_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='quantity',
        ),
    ]
